bases:
  - ../../base

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: alert-jira-gateway
    spec:
      replicas: 3
      template:
        spec:
          containers:
          - name: alert-jira-gateway
            image: alert-jira-gateway:prod